config/routes.rb
Rails.application.routes.draw do
  get 'user/show'

  get 'user/edit'

  devise_for :users
  get 'home/index'

   root 'home#index'

end

app/models/champion.rb
class Champion < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:region,:game_name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
require 'lol'
require 'unirest'
before_filter :authenticate_user!
  def index

  	@client = Lol::Client.new "#{ENV["lol_api"]}", {region: "na"}
  	@champs = @client.champion.get
  	@champ_name = Champion.all


  end


end

app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:game_name, :region, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:game_name, :region, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
	@icon = Unirest.get "https://na.api.pvp.net/api/lol/#{current_user.region}/v1.4/summoner/by-name/#{current_user.game_name}?api_key=#{ENV["lol_api"]}"
	@user_id = @icon.body["#{current_user.game_name}"]["id"]
  	@champs_played = Unirest.get "https://na.api.pvp.net/championmastery/location/NA1/player/#{@user_id}/topchampions?api_key=#{ENV["lol_api"]}"
 	@champs_info = @champs_played.body
 	@champ_name = Champion.all
 	if !@icon.body["status"].nil? && @icon.body["status"]["message"] == "Not Found"
 		@msg = "Username could not be found, please try agian"
 		redirect_to "/users/edit?message=#{@msg}"
 	else
 	@icon_id = @icon.body["#{current_user.game_name}"]["profileIconId"]
 	@current_version_data = Unirest.get "https://na.api.pvp.net/api/lol/static-data/na/v1.2/versions?api_key=#{ENV["lol_api"]}"
 	@current_version = @current_version_data.body[0]
 	@profile_icon_url = "http://ddragon.leagueoflegends.com/cdn#{@current_version}/img/profileicon/#{@icon_id}.png"
 	end
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<h1>Leggo Legends</h1>
<p>Champions that are on free champ rotation</p>
<% @champs.each do |x| %>
<% if x.free_to_play == true %>

<% @champ_name.each do |t| %>
<% if t.champ_id == x.id%>
<p><%=t.name%></p>
<%end%>
<%end%>
<%end%>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rito</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<h3>Welcome, <%=current_user.email%></h3>

<%= button_to "Log out", destroy_user_session_path, method: :delete%>
<%= link_to "Profile",user_show_path%>
<%end%>
<%= link_to "Home", root_path%>
<%= yield %>

</body>
</html>

app/views/user/_form.html.erb
<div>
<%= form_for :user, url: edit_user_registration_path do |f| %>
	<div class="field">
		<%= f.label "Username"%>
		<%= f.text_field :game_name %>
	</div>

	<div class="field">
		<%= f.label "Region"%>
		<%= f.select :region, ["BR", "EUNE", "EUW", "JP", "KR", "LAN", "LAS", "NA", "OCE", "RU", "TR"]%>
	</div>

	<div class="field">
		<%= f.submit "Update"%>
	</div>
	<%end%>
</div>

app/views/user/show.html.erb
<% if current_user%>
	<%= link_to "edit", edit_user_registration_path %>
<%end%>
<div>
	<h1>User#show</h1>
	<p>Find me in app/views/user/show.html.erb</p>
	<%= image_tag "#{@profile_icon_url}"%>
	<h3>Username:  <%=current_user.game_name%></h3>
	<h3>Email:  <%=current_user.email%></h3>
	<h4>Region:  <%=current_user.region%></h4>
	<%if @champs_info != []%>
		<h4> Most played champions </h4>
		<% @champs_info.each do |champ| %>
			<% @champ_name.each do |name| %>
				<% if champ["championId"] == name.champ_id%>
				<% @name = name.name.gsub(" ","")%>
				<h4><%= image_tag "http://ddragon.leagueoflegends.com/cdn/#{@current_version}/img/champion/#{@name}.png"%>
				<h4>Champion Name:  <%=name.name %></h4>
				<h4>Mastery Level: 	<%=champ["championLevel"]%></h4>
				<%end%>
			<%end%>
		<%end%>
	<% else %>
		<h3>We cannot get enough information to know your most played champs  </h3>
	<%end%>
</div>